CREATE SEQUENCE seq_general START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_log START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_temp START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


-- CENTRALES HIDROELÉCTRICAS
CREATE SEQUENCE seq_central START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- EMPLEADOS
CREATE SEQUENCE seq_empleado START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- EQUIPOS
CREATE SEQUENCE seq_equipo START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- CLIENTES
CREATE SEQUENCE seq_cliente START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- PROYECTOS RSE
CREATE SEQUENCE seq_proyecto START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- PROVEEDORES
CREATE SEQUENCE seq_proveedor START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- COMPRAS
CREATE SEQUENCE seq_compra START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- CONTRATOS DE ENERGÍA
CREATE SEQUENCE seq_contrato START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- FACTURACIÓN
CREATE SEQUENCE seq_factura START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
