-- Ejecutar como DBA (SYSTEM)
alter session set "_ORACLE_SCRIPT" = true;
CREATE USER ANDEHYDRO IDENTIFIED BY Contraseña1234
DEFAULT TABLESPACE USERS
QUOTA 10m ON USERS;

GRANT CONNECT, RESOURCE TO ANDEHYDRO;
GRANT CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE, CREATE TRIGGER, CREATE TABLE TO ANDEHYDRO;

-- Crear usuario con pocos privilegios
alter session set "_ORACLE_SCRIPT" = true;
CREATE USER OPERADOR IDENTIFIED BY Operador123
DEFAULT TABLESPACE USERS
QUOTA 5M ON USERS
PROFILE C##PRFLIMIT;

GRANT CREATE SESSION TO OPERADOR;
GRANT SELECT ANY TABLE TO OPERADOR;

-- Permisos más estrictos
--GRANT SELECT ON CENTRAL_HIDROELECTRICA TO OPERADOR;
--GRANT SELECT ON EMPLEADO TO OPERADOR;
--GRANT SELECT ON CLIENTE TO OPERADOR;
--GRANT INSERT ON FACTURACION TO OPERADOR;

